/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RoleRouteImport } from './routes/role'
import { Route as GithubCallbackRouteImport } from './routes/github-callback'
import { Route as GithubRouteImport } from './routes/github'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProjectsProjectIdRouteImport } from './routes/projects.$projectId'
import { Route as ProjectsProjectIdMilestonesMilestoneIdRouteImport } from './routes/projects.$projectId_.milestones.$milestoneId'

const RoleRoute = RoleRouteImport.update({
  id: '/role',
  path: '/role',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubCallbackRoute = GithubCallbackRouteImport.update({
  id: '/github-callback',
  path: '/github-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const GithubRoute = GithubRouteImport.update({
  id: '/github',
  path: '/github',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdRoute = ProjectsProjectIdRouteImport.update({
  id: '/projects/$projectId',
  path: '/projects/$projectId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsProjectIdMilestonesMilestoneIdRoute =
  ProjectsProjectIdMilestonesMilestoneIdRouteImport.update({
    id: '/projects/$projectId_/milestones/$milestoneId',
    path: '/projects/$projectId/milestones/$milestoneId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/github-callback': typeof GithubCallbackRoute
  '/role': typeof RoleRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId/milestones/$milestoneId': typeof ProjectsProjectIdMilestonesMilestoneIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/github-callback': typeof GithubCallbackRoute
  '/role': typeof RoleRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId/milestones/$milestoneId': typeof ProjectsProjectIdMilestonesMilestoneIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/github': typeof GithubRoute
  '/github-callback': typeof GithubCallbackRoute
  '/role': typeof RoleRoute
  '/projects/$projectId': typeof ProjectsProjectIdRoute
  '/projects/$projectId_/milestones/$milestoneId': typeof ProjectsProjectIdMilestonesMilestoneIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/github'
    | '/github-callback'
    | '/role'
    | '/projects/$projectId'
    | '/projects/$projectId/milestones/$milestoneId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/github'
    | '/github-callback'
    | '/role'
    | '/projects/$projectId'
    | '/projects/$projectId/milestones/$milestoneId'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/dashboard'
    | '/github'
    | '/github-callback'
    | '/role'
    | '/projects/$projectId'
    | '/projects/$projectId_/milestones/$milestoneId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  GithubRoute: typeof GithubRoute
  GithubCallbackRoute: typeof GithubCallbackRoute
  RoleRoute: typeof RoleRoute
  ProjectsProjectIdRoute: typeof ProjectsProjectIdRoute
  ProjectsProjectIdMilestonesMilestoneIdRoute: typeof ProjectsProjectIdMilestonesMilestoneIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/role': {
      id: '/role'
      path: '/role'
      fullPath: '/role'
      preLoaderRoute: typeof RoleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github-callback': {
      id: '/github-callback'
      path: '/github-callback'
      fullPath: '/github-callback'
      preLoaderRoute: typeof GithubCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/github': {
      id: '/github'
      path: '/github'
      fullPath: '/github'
      preLoaderRoute: typeof GithubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId': {
      id: '/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/projects/$projectId'
      preLoaderRoute: typeof ProjectsProjectIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$projectId_/milestones/$milestoneId': {
      id: '/projects/$projectId_/milestones/$milestoneId'
      path: '/projects/$projectId/milestones/$milestoneId'
      fullPath: '/projects/$projectId/milestones/$milestoneId'
      preLoaderRoute: typeof ProjectsProjectIdMilestonesMilestoneIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  GithubRoute: GithubRoute,
  GithubCallbackRoute: GithubCallbackRoute,
  RoleRoute: RoleRoute,
  ProjectsProjectIdRoute: ProjectsProjectIdRoute,
  ProjectsProjectIdMilestonesMilestoneIdRoute:
    ProjectsProjectIdMilestonesMilestoneIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
